#!/usr/bin/env python3
"""Genesis dev — sprite review tool (server half).

Serves dev/sprite-review.html plus a tiny JSON API that acts DIRECTLY on the repo —
no copy-paste round-trips:

  GET  /                → the review UI
  GET  /sprites/<slug>.png → the cut sprite from assets/sprites/
  GET  /sprites-prev/<slug>.png → the PRE-recut backup from
                          dev/sprite-manifests/review/prev/ (404 when absent) — SPRITE-RESCUE
                          U3's before copy, for the U4 A/B toggle
  GET  /api/data        → { registry, overlay, magenta, triage, prev } — SPRITE_REGISTRY (parsed
                          out of data/sprite-registry.js via a node one-liner) deep-merged
                          view, the raw overlay, the parsed magenta-scan.json (SPRITE-RESCUE
                          U1, `{}` if not yet generated), the parsed magenta-triage.json
                          (U6, `{}` if not yet generated), and `prev` — the list of slugs that
                          have a backup under dev/sprite-manifests/review/prev/ (`[]` if the
                          dir doesn't exist yet)
  POST /api/overlay     → body {"slug": "...", "set": {...}, "clear": ["key", ...]}
                          merges into dev/model-qa/sprite-tags-overlay.json (atomic write).
                          Recognized keys: scale (number, per-slug billboard height multiplier
                          — the heads-line-up calibration), verdict ("pass"|"fail"), note,
                          tags (list), redlined (bool). An entry emptied of every key is removed.
  POST /api/regen       → runs build/gen-sprite-registry.py so the overlay folds into
                          data/sprite-registry.js (what the theater actually reads).

The overlay file is the ONLY thing this server writes (plus the regen side effect above).
Registry/manifest stay generated-only per the repo discipline.

Rescue flow (SPRITE-RESCUE D4): a recut sprite that had verdict:"fail" gets re-ruled in this
tool; on PASS the overlay flips, and the wave close re-runs build/gen-xl-regen-sheets.py so
the slug leaves the REDO tier.

Run:  python3 dev/sprite-review.py   → http://127.0.0.1:5179/
"""

import json
import os
import re
import subprocess
import sys
import tempfile
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY_JS = os.path.join(ROOT, "data", "sprite-registry.js")
OVERLAY = os.path.join(ROOT, "dev", "model-qa", "sprite-tags-overlay.json")
SPRITES_DIR = os.path.join(ROOT, "assets", "sprites")
UI_HTML = os.path.join(ROOT, "dev", "sprite-review.html")
MAGENTA_SCAN = os.path.join(ROOT, "dev", "sprite-manifests", "magenta-scan.json")
MAGENTA_TRIAGE = os.path.join(ROOT, "dev", "sprite-manifests", "magenta-triage.json")
PREV_DIR = os.path.join(ROOT, "dev", "sprite-manifests", "review", "prev")
PORT = 5179

SLUG_RE = re.compile(r"^spr-[a-z0-9-]+$")


def parse_registry():
    """data/sprite-registry.js is a JS object literal (unquoted keys) — let node eval it
    and hand back JSON rather than half-parsing JS in Python."""
    script = (
        'const fs=require("fs");'
        f'const src=fs.readFileSync({json.dumps(REGISTRY_JS)},"utf8");'
        'eval(src.replace(/const SPRITE_REGISTRY=/,"globalThis.SPRITE_REGISTRY="));'
        "process.stdout.write(JSON.stringify(globalThis.SPRITE_REGISTRY));"
    )
    out = subprocess.run(["node", "-e", script], capture_output=True, text=True, cwd=ROOT)
    if out.returncode != 0:
        raise RuntimeError(f"node failed to parse {REGISTRY_JS}: {out.stderr[:500]}")
    return json.loads(out.stdout)


def load_overlay():
    if not os.path.exists(OVERLAY):
        return {}
    with open(OVERLAY, encoding="utf-8") as f:
        return json.load(f)


def load_json_or_empty(path):
    """Never a crash — SPRITE-RESCUE's scan/triage files are generated by separate
    scripts that may not have run yet."""
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def list_prev():
    """Slugs with a pre-recut backup under dev/sprite-manifests/review/prev/ (U3's before
    copy). Never a crash — the dir doesn't exist until the first recut runs."""
    if not os.path.isdir(PREV_DIR):
        return []
    out = []
    for name in os.listdir(PREV_DIR):
        if name.endswith(".png") and SLUG_RE.match(name[:-4]):
            out.append(name[:-4])
    return sorted(out)


def save_overlay(data):
    """Atomic write (tmp + rename) so a mid-write crash never corrupts the redline surface."""
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(OVERLAY), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False, sort_keys=True)
            f.write("\n")
        os.replace(tmp, OVERLAY)
    finally:
        if os.path.exists(tmp):
            os.remove(tmp)


ALLOWED_KEYS = {"scale", "verdict", "note", "tags", "redlined", "reusable", "groundOffset"}


def apply_patch(slug, set_keys, clear_keys):
    if not SLUG_RE.match(slug or ""):
        raise ValueError(f"bad slug: {slug!r}")
    data = load_overlay()
    entry = dict(data.get(slug) or {})
    for k, v in (set_keys or {}).items():
        if k not in ALLOWED_KEYS:
            raise ValueError(f"unknown overlay key: {k}")
        if k == "scale":
            v = float(v)
            if not (0.05 <= v <= 10):
                raise ValueError(f"scale out of range: {v}")
            if abs(v - 1.0) < 1e-9:  # scale 1 = no calibration; keep the overlay sparse
                entry.pop("scale", None)
                continue
        if k == "groundOffset":
            v = float(v)
            if not (0 <= v <= 0.5):
                raise ValueError(f"groundOffset out of range: {v}")
            if abs(v) < 1e-9:  # 0 = no offset; keep the overlay sparse
                entry.pop("groundOffset", None)
                continue
        if k == "verdict" and v not in ("pass", "fail"):
            raise ValueError(f"verdict must be pass|fail, got {v!r}")
        if k == "tags" and not (isinstance(v, list) and all(isinstance(t, str) for t in v)):
            raise ValueError("tags must be a list of strings")
        if k == "note" and not isinstance(v, str):
            raise ValueError("note must be a string")
        entry[k] = v
    for k in clear_keys or []:
        entry.pop(k, None)
    if entry:
        data[slug] = entry
    else:
        data.pop(slug, None)
    save_overlay(data)
    return entry


class Handler(BaseHTTPRequestHandler):
    def _send(self, code, body, ctype="application/json"):
        payload = body if isinstance(body, bytes) else json.dumps(body).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(payload)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, fmt, *args):  # keep the console readable
        path = args[0] if args else ""
        if "/sprites/" not in path and "/sprites-prev/" not in path:
            sys.stderr.write("[review] " + (fmt % args) + "\n")

    def do_GET(self):
        try:
            if self.path in ("/", "/index.html"):
                with open(UI_HTML, "rb") as f:
                    self._send(200, f.read(), "text/html; charset=utf-8")
            elif self.path.startswith("/sprites/"):
                name = os.path.basename(self.path)
                if not (name.endswith(".png") and SLUG_RE.match(name[:-4])):
                    self._send(404, {"error": "bad sprite path"})
                    return
                p = os.path.join(SPRITES_DIR, name)
                if not os.path.exists(p):
                    self._send(404, {"error": "no such sprite"})
                    return
                with open(p, "rb") as f:
                    self._send(200, f.read(), "image/png")
            elif self.path.startswith("/sprites-prev/"):
                name = os.path.basename(self.path)
                if not (name.endswith(".png") and SLUG_RE.match(name[:-4])):
                    self._send(404, {"error": "bad sprite path"})
                    return
                p = os.path.join(PREV_DIR, name)
                if not os.path.exists(p):
                    self._send(404, {"error": "no such prev sprite"})
                    return
                with open(p, "rb") as f:
                    self._send(200, f.read(), "image/png")
            elif self.path == "/api/data":
                self._send(200, {
                    "registry": parse_registry(), "overlay": load_overlay(),
                    "magenta": load_json_or_empty(MAGENTA_SCAN),
                    "triage": load_json_or_empty(MAGENTA_TRIAGE),
                    "prev": list_prev(),
                })
            elif self.path == "/rejects":
                p = os.path.join(ROOT, "dev", "sprite-manifests", "REJECTS.md")
                body = open(p, "rb").read() if os.path.exists(p) else \
                    b"No REJECTS.md yet - hit 'regen registry' after failing something."
                self._send(200, body, "text/plain; charset=utf-8")
            else:
                self._send(404, {"error": "not found"})
        except Exception as e:  # dev tool: surface the error to the UI, don't die
            self._send(500, {"error": str(e)})

    def do_POST(self):
        try:
            n = int(self.headers.get("Content-Length") or 0)
            body = json.loads(self.rfile.read(n) or b"{}")
            if self.path == "/api/overlay":
                entry = apply_patch(body.get("slug"), body.get("set"), body.get("clear"))
                self._send(200, {"ok": True, "slug": body.get("slug"), "entry": entry})
            elif self.path == "/api/regen":
                out = subprocess.run(
                    [sys.executable, os.path.join(ROOT, "build", "gen-sprite-registry.py")],
                    capture_output=True, text=True, cwd=ROOT, timeout=120,
                )
                self._send(200 if out.returncode == 0 else 500, {
                    "ok": out.returncode == 0,
                    "stdout": out.stdout[-2000:], "stderr": out.stderr[-2000:],
                })
            else:
                self._send(404, {"error": "not found"})
        except Exception as e:
            self._send(500, {"error": str(e)})


def main():
    port = int(sys.argv[1]) if len(sys.argv) > 1 else PORT
    parse_registry()  # fail fast if node/registry is broken, before claiming the port
    srv = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    print(f"sprite review → http://127.0.0.1:{port}/  (overlay: {os.path.relpath(OVERLAY, ROOT)})")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
