/* GENESIS MODULE — src/ui/ref-wiki.js — the Wiki reference app (REFERENCE-SHELF.md unit S3).
   Classic <script>, shared global scope. Registers ONE REFERENCE_APPS entry via
   referenceShelfRegister({id:'wiki', label:'Wiki', order:2, mount, teardown}) — the framework
   (src/ui/reference-shelf.js, unit S1) owns the shell/overlay/lifecycle; this module only owns
   what renders inside #refShelfBody once mounted.

   Data: data/wiki.js (owns WIKI_INDEX, generated by build/gen-wiki.py from docs/ARCHITECTURE.md
   — edit-source→compile-artifact; never hand-edit data/wiki.js).

   v1 (per docs/REFERENCE-SHELF.md "Registered app #2 — Wiki"): index + simple description.
     - Left nav: systems grouped by layer.
     - Main panel: the selected system's card (whatItIs, howItWorks, livesIn, spec link).
     - Free-text filter over system name + whatItIs + howItWorks; a layer filter.
     - Each card carries a "full detail →" affordance: resolves to the linked spec doc (v1: a
       read-only pointer/label — the actual spec-doc RENDERER is a fast-follow, not v1) or a
       "detail page coming" stub when spec is null. slug + spec already ride the data shape so
       routing is a later add, not a reshape.

   Owns exactly: (nothing global beyond registering into REFERENCE_APPS — no new owned symbols
   besides the registration side-effect). Internal state (_refWikiFilter, _refWikiLayer,
   _refWikiSelected) is module-local to this file, not exposed via manifest `owns`. */

(function () {
  var _refWikiFilter = "";
  var _refWikiLayer = "";
  var _refWikiSelected = null; // slug of the selected system, or null (no selection yet)

  function _refWikiLayers() {
    var seen = [];
    (typeof WIKI_INDEX !== "undefined" ? WIKI_INDEX : []).forEach(function (e) {
      if (seen.indexOf(e.layer) === -1) seen.push(e.layer);
    });
    return seen;
  }

  function _refWikiMatches(entry, filterText) {
    if (!filterText) return true;
    var hay = (entry.system + " " + entry.whatItIs + " " + entry.howItWorks).toLowerCase();
    return hay.indexOf(filterText.toLowerCase()) !== -1;
  }

  function _refWikiFiltered() {
    var all = typeof WIKI_INDEX !== "undefined" ? WIKI_INDEX : [];
    return all.filter(function (e) {
      if (_refWikiLayer && e.layer !== _refWikiLayer) return false;
      return _refWikiMatches(e, _refWikiFilter);
    });
  }

  function _refWikiEscapeHtml(s) {
    return String(s == null ? "" : s)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  function _refWikiNavHTML(container) {
    var filtered = _refWikiFiltered();
    var byLayer = {};
    var layerOrder = [];
    filtered.forEach(function (e) {
      if (!byLayer[e.layer]) { byLayer[e.layer] = []; layerOrder.push(e.layer); }
      byLayer[e.layer].push(e);
    });

    var layers = _refWikiLayers();
    var layerOptions = ['<option value="">All layers</option>'].concat(
      layers.map(function (l) {
        var sel = l === _refWikiLayer ? " selected" : "";
        return '<option value="' + _refWikiEscapeHtml(l) + '"' + sel + ">" + _refWikiEscapeHtml(l) + "</option>";
      })
    ).join("");

    var groups = layerOrder.map(function (layer) {
      var items = byLayer[layer].map(function (e) {
        var active = e.slug === _refWikiSelected ? " active" : "";
        return (
          '<button class="btn ghost sm refwiki-nav-item' + active + '" ' +
          'onclick="_refWikiSelect(\'' + e.slug + '\')" ' +
          'aria-current="' + (e.slug === _refWikiSelected ? "true" : "false") + '">' +
          _refWikiEscapeHtml(e.system) +
          "</button>"
        );
      }).join("");
      return (
        '<div class="refwiki-nav-group">' +
        '<div class="refwiki-nav-layer">' + _refWikiEscapeHtml(layer) + "</div>" +
        '<div class="refwiki-nav-items">' + items + "</div>" +
        "</div>"
      );
    }).join("");

    return (
      '<div class="refwiki-nav" role="navigation" aria-label="Wiki systems">' +
      '<div class="refwiki-controls">' +
      '<input type="text" class="refwiki-search" placeholder="Search systems…" ' +
      'aria-label="Search the Wiki" value="' + _refWikiEscapeHtml(_refWikiFilter) + '" ' +
      'oninput="_refWikiSetFilter(this.value)" />' +
      '<select class="refwiki-layer-select" aria-label="Filter by layer" onchange="_refWikiSetLayer(this.value)">' +
      layerOptions +
      "</select>" +
      "</div>" +
      '<div class="refwiki-nav-scroll">' +
      (groups || '<div class="refwiki-empty">No systems match.</div>') +
      "</div>" +
      "</div>"
    );
  }

  function _refWikiCardHTML() {
    var all = typeof WIKI_INDEX !== "undefined" ? WIKI_INDEX : [];
    var entry = null;
    if (_refWikiSelected) {
      entry = all.filter(function (e) { return e.slug === _refWikiSelected; })[0] || null;
    }
    if (!entry) {
      return (
        '<div class="refwiki-card refwiki-card-empty">' +
        "<p>Select a system from the list to read its entry.</p>" +
        "</div>"
      );
    }

    var livesInHTML = (entry.livesIn || [])
      .map(function (p) { return "<code>" + _refWikiEscapeHtml(p) + "</code>"; })
      .join(", ");

    var detailHTML;
    if (entry.spec) {
      detailHTML =
        '<a class="btn ghost sm refwiki-detail-link" href="' + _refWikiEscapeHtml(entry.spec) + '" ' +
        'target="_blank" rel="noopener" data-slug="' + _refWikiEscapeHtml(entry.slug) + '">' +
        "full detail → " + _refWikiEscapeHtml(entry.spec) +
        "</a>";
    } else {
      detailHTML =
        '<span class="refwiki-detail-stub" data-slug="' + _refWikiEscapeHtml(entry.slug) + '">' +
        "detail page coming" +
        "</span>";
    }

    return (
      '<article class="refwiki-card" aria-labelledby="refWikiCardTitle">' +
      '<div class="refwiki-card-layer">' + _refWikiEscapeHtml(entry.layer) + "</div>" +
      '<h3 id="refWikiCardTitle" class="refwiki-card-title">' + _refWikiEscapeHtml(entry.system) + "</h3>" +
      '<p class="refwiki-card-what"><strong>What it is.</strong> ' + _refWikiEscapeHtml(entry.whatItIs) + "</p>" +
      '<p class="refwiki-card-how"><strong>How it works.</strong> ' + _refWikiEscapeHtml(entry.howItWorks) + "</p>" +
      '<p class="refwiki-card-lives"><strong>Lives in:</strong> ' + livesInHTML + "</p>" +
      '<div class="refwiki-card-detail">' + detailHTML + "</div>" +
      "</article>"
    );
  }

  function _refWikiRender(container) {
    if (!container) return;
    container.innerHTML =
      '<div class="refwiki-root">' +
      _refWikiNavHTML(container) +
      '<div class="refwiki-main">' + _refWikiCardHTML() + "</div>" +
      "</div>";
  }

  // -- event handlers, global so inline handlers can reach them (same convention as the rest
  //    of the classic-script UI layer) --
  function _refWikiSelect(slug) {
    _refWikiSelected = slug;
    _refWikiRender(document.getElementById("refShelfBody"));
  }

  function _refWikiSetFilter(text) {
    _refWikiFilter = text || "";
    _refWikiRender(document.getElementById("refShelfBody"));
  }

  function _refWikiSetLayer(layer) {
    _refWikiLayer = layer || "";
    _refWikiRender(document.getElementById("refShelfBody"));
  }

  // expose the handlers globally (classic-script convention — inline onclick/oninput need them)
  if (typeof window !== "undefined") {
    window._refWikiSelect = _refWikiSelect;
    window._refWikiSetFilter = _refWikiSetFilter;
    window._refWikiSetLayer = _refWikiSetLayer;
  } else if (typeof globalThis !== "undefined") {
    globalThis._refWikiSelect = _refWikiSelect;
    globalThis._refWikiSetFilter = _refWikiSetFilter;
    globalThis._refWikiSetLayer = _refWikiSetLayer;
  }

  function _refWikiMount(container) {
    _refWikiFilter = "";
    _refWikiLayer = "";
    _refWikiSelected = null;
    _refWikiRender(container);
  }

  function _refWikiTeardown(container) {
    if (container) container.innerHTML = "";
    _refWikiFilter = "";
    _refWikiLayer = "";
    _refWikiSelected = null;
  }

  if (typeof referenceShelfRegister === "function") {
    referenceShelfRegister({
      id: "wiki",
      label: "Wiki",
      icon: "📖",
      order: 2,
      mount: _refWikiMount,
      teardown: _refWikiTeardown,
    });
  }
})();
