#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
import numpy as np
from PIL import Image
H=Path(__file__).resolve().parent;R=H.parent.parent;sm=json.loads((H/"manifests/b01-timber-shingle-v001.source.json").read_text());mm=json.loads((H/"manifests/b01-timber-shingle-mm-v001.source.json").read_text());runs=[H/"exports/b01-timber-shingle-mm-v001/run-a",H/"exports/b01-timber-shingle-mm-v001/run-b"];stem="b01-roof-timber-shingle-v001";names={k:f"{stem}_{v}.png" for k,v in {"albedo":"albedo","height":"heightmap","normal":"normal","orm":"orm"}.items()};sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
for n in names.values():
    if not all((r/n).exists() for r in runs) or sha(runs[0]/n)!=sha(runs[1]/n):raise RuntimeError(f"missing or nondeterministic {n}")
src=np.asarray(Image.open(R/mm["source"]).convert("RGB"),float);alb=np.asarray(Image.open(runs[0]/names["albedo"]).convert("RGB"),float);hei=np.asarray(Image.open(runs[0]/names["height"]).convert("L"),float);nor=np.asarray(Image.open(runs[0]/names["normal"]).convert("RGB"),float);orm=np.asarray(Image.open(runs[0]/names["orm"]).convert("RGB"),float);mae=float(abs(src-alb).mean());corr=float(np.corrcoef(src.reshape(-1),alb.reshape(-1))[0,1]);rough=round(mm["materialTreatment"]["roughness"]*255);identity=mae<3 and corr>.99;seam=sm["acceptedSource"]["technicalGate"]=="PASS";depth=hei.std()>1 and max(nor[:,:,0].std(),nor[:,:,1].std())>.35;ormok=orm[:,:,2].max()==0 and abs(orm[:,:,1].mean()-rough)<=1;passed=identity and seam and depth and ormok;report={"schemaVersion":1,"assetId":mm["assetId"],"result":"PASS" if passed else "FAIL","sourceIdentity":{"meanAbsoluteError":round(mae,4),"pixelCorrelation":round(corr,4),"preserved":bool(identity)},"inheritedSourceSeamGate":{"passed":bool(seam)},"depth":{"heightStdDev":round(float(hei.std()),4),"normalStdDevRgb":[round(float(v),4) for v in nor.std(axis=(0,1))],"broadSignalPresent":bool(depth)},"orm":{"expectedRoughnessByte":rough,"metallicMaxByte":int(orm[:,:,2].max()),"valid":bool(ormok)}};(H/"receipts/b01-timber-shingle-mm-v001-verification.json").write_text(json.dumps(report,indent=2)+"\n");print(f"{report['result']}: timber-shingle MM verification")
