#!/usr/bin/env node
import fs from "node:fs";
import http from "node:http";
import path from "node:path";
import {createRequire} from "node:module";
import {fileURLToPath} from "node:url";
const __dirname=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(__dirname,"../..");
const req=createRequire(path.join(process.env.HOME,".genesis-jsdom","package.json")),puppeteer=req("puppeteer-core");
const server=http.createServer((request,response)=>{const pathname=decodeURIComponent(new URL(request.url,"http://localhost").pathname),file=path.resolve(root,"."+pathname);if(!file.startsWith(root+path.sep)){response.writeHead(403);response.end();return}fs.readFile(file,(error,data)=>{if(error){response.writeHead(404);response.end();return}response.writeHead(200,{"Content-Type":path.extname(file)===".html"?"text/html":path.extname(file)===".js"?"text/javascript":path.extname(file)===".glb"?"model/gltf-binary":"application/octet-stream"});response.end(data)})});
await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
const browser=await puppeteer.launch({executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",headless:"new",args:["--use-angle=swiftshader","--enable-webgl","--ignore-gpu-blocklist","--no-sandbox","--disable-gpu-sandbox"]});
try{const page=await browser.newPage();await page.setViewport({width:1200,height:900,deviceScaleFactor:1});await page.goto(`http://127.0.0.1:${server.address().port}/dev/model-foundry/extruded-prop-viewer.html`,{waitUntil:"networkidle0"});await page.waitForFunction(()=>window.__ready===true);const report=JSON.parse(fs.readFileSync(path.join(__dirname,"extruded-props/proof-report.json"),"utf8")),entries=report.proof.filter(item=>item.technicalStatus==="COMPILED");await page.evaluate(batch=>window.renderProof(batch),entries);await page.screenshot({path:path.join(__dirname,"extruded-props/proof-contact-sheet.png")});console.log(`captured ${entries.length} technical-only props`);const library=JSON.parse(fs.readFileSync(path.join(__dirname,"extruded-props/library-report.json"),"utf8")).assets.filter(item=>item.technicalStatus==="COMPILED"),libraryOut=path.join(__dirname,"extruded-props/library-contact-sheets");fs.mkdirSync(libraryOut,{recursive:true});for(let offset=0;offset<library.length;offset+=9){const batch=library.slice(offset,offset+9);await page.evaluate(items=>window.renderProof(items),batch);const file=`library-${String(offset/9+1).padStart(2,"0")}.png`;await page.screenshot({path:path.join(libraryOut,file)});console.log(`captured ${file} (${Math.min(offset+9,library.length)}/${library.length})`)}}finally{await browser.close();server.close()}
